### ISSUE TITLE
When both  StuckOnLoadingPartUpgradesFix and KSPCommunityFixes, loading saves fails to load the vessels

### ISSUE THREAD

**Issue by gbesacier** [KSPModdingLibs/KSPCommunityFixes#103]
There is an interaction going on between KSPCommunityFixes and https://github.com/gotmachine/StuckOnLoadingPartUpgradesFix

I tested on a new Steam install of KSP 1.12.3, without any mod except ModuleManager 4.2.2, Harmony, and KSPCommunityFixes 1.23 (all installed from CKAN), and StuckOnLoadingPartUpgradesFix 1.1 (installed from the Github release).

Test case: 
- Create a new sandbox game
- Create a rocket in the VAB and change some attributes of the part (for my test case, I put a RoverMax with the non-default gold skin and a Mk1 Pod with the lights on and the flag mirrored)
- Launch the rocket
- Quicksave
- Quickload
- The RoverMax has its default white skin, the lights of the Mk1Pod is off, and the flag is no longer mirrored
- Exit KSP
- Remove KSPCommunityFixes folder
- Restart KSP, load your sandbox game, load the existing quicksave
- All the parts are loaded properly with all their attributes (so the bug is not in the saving process but in the loading process)
- Exit KSP
- Re-add KSPCommunityFixes
- Removed StuckOnLoadingPartUpgradesFix files (2 files and 1 folder)
- Restart KSP, load your sandbox game, load the quicksave
- All the parts are also loaded properly with all their attributes

The bug affect all modifications you can do with the little attribute popup, whether you do then in the VAB/SPH or during the flight, and whether it's a stock attribute or a mod attribute (originally I found the bug because of TweakScale: on load, parts have their default size)

**Comment by gbesacier** [comment]
Issue in the other mod repository gotmachine/StuckOnLoadingPartUpgradesFix#1

**Comment by gbesacier** [comment]
I still have the stock bug with 1.12.3 personally. From what I understand, StuckOnLoadingPartUpgradesFix fixes two bugs: duplicate DLLs and non-managed DLLs. Maybe stock fixed the duplicate DLLs issue, but the non-managed DLLs issue is still here. The mod Principia (which I consider a must-have) is using non-managed (native) DLLs. If I remove it KSP 1.12.3 loads, if I don't remove it KSP 1.12.3 hangs on "part upgrades"

**Comment by gotmachine** [comment]
Sounds like an install issue, Principia is working fine on 1.12.3 for everyone else.

In any case, the StuckOnLoadingPartUpgradesFix mod will indeed conflict with any mod using the latest HarmonyKSP (because it package an outdated version). It's true that the non-managed handling isn't fixed in 1.12.3, but as far as I know all mods that would have been affected (including Principia) have implemented workarounds.

**Comment by gbesacier** [comment]
You're right, I finally found the culprit: a stray native DLL from an older version of Principia, so without the workaround (they renamed a DLL at some point, and as I'm copying the new versions over the old ones it was left behind)
