### ISSUE TITLE
Cannot dismiss or disable FastLoader opt-in popup on KSP < 1.12.0

### ISSUE THREAD

**Issue by peterhaneve** [KSPModdingLibs/KSPCommunityFixes#112]
## Issue
On KSP versions under 1.12.0 (tested on KSP 1.11.1, Windows x64, KSP Community Fixes 1.24.0), the FastLoader patch will not be available. However, the opt-in dialog appears on every startup asking to opt-in to PNG texture caching and cannot be dismissed as both buttons cause an exception on click. Manually creating the file `KSPCommunityFixes/PluginData/PNGTextureCache.cfg` also does not work, as the patch only attempts to read and parse the file if KSP is 1.12 or higher.

## Resolution
Only show the opt-in dialog (https://github.com/KSPModdingLibs/KSPCommunityFixes/blob/master/KSPCommunityFixes/Performance/FastLoader.cs#L132) if `IsPatchEnabled` is `true`. `OnDestroy` could probably also evade an unnecessary Harmony call as well with a similar condition.

**Comment by gotmachine** [comment]
Whoops. Will push a fixed release.
