### ISSUE TITLE
game stuck on "loading sound asset"

### ISSUE THREAD

**Issue by dawn0303** [KSPModdingLibs/KSPCommunityFixes#117]
on ksp version 1.12.5
![image](https://user-images.githubusercontent.com/60470011/215165347-596bcbeb-ecb5-4ca3-ba43-2d07055c982b.png)
whenever I have harmony installed the game never loads past this message, I'm not sure whats causing it or what to do

**Comment by gotmachine** [comment]
This is a KSPCommunityFixes issue, not a Harmony issue.
Please provide your KSP.log file, there is literally nothing I can do with the information you provided.

**Comment by dawn0303** [comment]
[KSP.log](https://github.com/KSPModdingLibs/KSPCommunityFixes/files/10522811/KSP.log)
sorry about that, I'm new at this, here's my log, lmk if u need anything else

**Comment by gotmachine** [comment]
Ok, I think I found the issue.

In `GameData/SMI_MissilesLaunchers/Sounds`, you likely have two files named `rocketLoopSoft`, one with the `.wav` extension, and another with likely a `.ogg` extension. Delete one of them (won't break anything), this should fix the issue and confirm what I'm suspecting is going wrong in KSPCommunityFixes. 

Please report back if that fixes the issue.

**Comment by dawn0303** [comment]
all fixed! also somehow fixed some other issues that i assumed were unrelated

**Comment by gotmachine** [comment]
Thanks for reporting, issue fixed in KSPCF 1.24.4
