### ISSUE TITLE
Altimeter Position is reset after every revert

### ISSUE THREAD

**Issue by Clayell** [KSPModdingLibs/KSPCommunityFixes#125]
**Describe your problem with KSPCF :** Every time I change the position of the altimeter, it resets the next revert and I have to fix it again. The actual slider within the settings doesn't change, as moving it even a little bit causes the altimeter to snap back to its original position. This doesn't seem to happen after a new game session, as manually changing the altimeter position within the cfg file causes it to be at the correct position for that one launch. (but as stated previously, every launch after that will be at a bugged position) For now, I'm just going to disable this patch in the settings so it isn't bugging out every single time.

Images: 
[Fixed position on launch 1](https://cdn.discordapp.com/attachments/617156220146417664/1084602684407033987/image.png)
[Bugged position on launch 2](https://cdn.discordapp.com/attachments/617156220146417664/1084612559979687936/image.png)

**KSP version :** 1.12.5
**Link to your `KSP.log` file :** https://drive.google.com/file/d/1joQyonUvv0GjtcAjYN8L4lzAwWFwFbXf/view?usp=share_link

**Comment by gotmachine** [comment]
I can't reproduce this.

TBH, your install is extremely bloated and your log is full of errors and exceptions, including repeating exceptions in rather core KSP subsystems.

I don't exclude a mod compatibility issue, but the altimeter position feature has been in KSPCF since nearly 2 years, it's probable it failing totally at what it's supposed to do would have been reported already.

Let me know if you manage to reproduce this in a stock install or if you identify a specific mod incompatibility.

**Comment by Clayell** [comment]
alright ill be on the lookout for that
where do you see the errors by the way?

**Comment by gotmachine** [comment]
Ok, I see the issue. The position isn't actually reset like you said, it's just that the position you set while in the settings menu is slightly offset compared to the one you get after, the reason being that the width of the stock app/mod launcher toolbar on the right is accounted for in one case and not the other.

Will push a fix for that, thanks for the report.

> where do you see the errors by the way?

More or less everywhere. Tons of asset errors ModularLaunchPads, TundraSpaceCenter and OSSNTR.
Runtime errors in mods like Scatterer, TextureUnlimited, Kerbalism, TransferWindowPlanner, KerbalChangelog
You have repeating errors in the KSP mouse input handler.
Thousands of repeating errors from DecouplerLight

**Comment by Clayell** [comment]
nice! im glad i was able to report something broken

ill report these bugs to their respective mod owners
> More or less everywhere. Tons of asset errors ModularLaunchPads, TundraSpaceCenter and OSSNTR. Runtime errors in mods like Scatterer, TextureUnlimited, Kerbalism, TransferWindowPlanner, KerbalChangelog You have repeating errors in the KSP mouse input handler. Thousands of repeating errors from DecouplerLight

**Comment by Clayell** [comment]
after some testing, i can confirm this was fixed on my machine
many thanks for the fix!
