### ISSUE TITLE
Toggle Active/Offered Waypoints/Orbits on Tracking Station

### ISSUE THREAD

**Issue by eusouaverdade** [KSPModdingLibs/KSPCommunityFixes#132]
**Provide a description of the KSP bug or improvement**
Those 4 buttons apparently should hidde and show the Orbits and Waypoints of active and offered contracts but I can't remember a version that they worked.

![Sem título](https://user-images.githubusercontent.com/13490476/227830873-7013b098-46c1-43b8-b491-e7f3ea9937e3.png)

**Comment by gotmachine** [comment]
Yeah this is a ContractConfigurator thing

**Comment by eusouaverdade** [comment]
Oh boy, what a rockie mistake, I have ContractConfigurator indeed, thanks.
