### ISSUE TITLE
Bugfix - Locked autostruts on landing gears

### ISSUE THREAD

**Issue by hohmannson** [KSPModdingLibs/KSPCommunityFixes#16]
Landing gears and wheels using stock module have their autostrut settings locked to "enabled" and "to most massive part". It's not safe in some situations(mostly docking of spaceplanes with big stuff) and may even cause krakens with legs being displaced on rocket spawn. It seems to be hardcoded, can't fix it through configs.

**Comment by gotmachine** [comment]
So what are you asking ?

To have the wheels autostrut PAW setting made available like on regular parts ?

**Comment by gotmachine** [comment]
Implemented in release 1.2.0 : autostrut PAW option is now user-modifiable on wheels/legs, but still set to "heaviest part" by default.

Changing it doesn't seem to cause obvious side effects.
