### ISSUE TITLE
[ReflectionTypeLoadExceptionHandler] : detect loading of incompatible assemblies 

### ISSUE THREAD

**Issue by gotmachine** [KSPModdingLibs/KSPCommunityFixes#168]
Currently, the ReflectionTypeLoadExceptionHandler patch will inform the user if an assembly failed to load like this : 
```
[WRN 15:24:04.746] [KSPCF] A ReflectionTypeLoadException thrown by Assembly.GetTypes() has been handled by KSP Community Fixes.
This is usually harmless, but indicates that the "SolarSailNavigator" plugin failed to load (location: "GameData\SolarSailNavigator\Plugins\SolarSailNavigator.dll")
```
This is fine in the context of an assembly that failed to load due to missing dependency, but in the case of .Net Framework version mismatch (ie, loading a pre-1.8 assembly itself loading some bundled .Net assembly), the "This is usually harmless" wording definitely is bad choice, as such a case usually end up with a very broken KSP.

We could probably detect the framework against which the plugin was built, and adapt the messaging accordingly, both on-screen and in the logs.

**Comment by JonnyOThan** [comment]
I love this idea.  Would it also be possible to repair KSP itself, by removing the offending assembly from the loaded assembly list?  Or does that already happen, and the damage is already done?

**Comment by gotmachine** [comment]
There is no way to unload an assembly, the damage can't be undone AFAIK.

**Comment by gotmachine** [comment]
I've been looking a bit at this, but the situation isn't as straightforward as it may seems.
There is nothing fundamentally wrong in loading plugins that were built against .NET 3.5 or even 2.0, as the .NET public API is backward compatible all the way down.

I think actual issues boil down to a variety of factors. It could be that a plugin is bundling some outdated framework assembly (KSP doesn't come with a full distribution), in which case things often go quite wrong, it could be that a plugin is calling some "unofficial" framework API that did actually change in a breaking way between versions (the mono BCL has a tendency to exposes publicly additional stuff compared to the .Net framework API surface, but only that API surface is guaranteed to be backward compatible).
Other cases might sketchy code that was previously relying on undefined behavior and working by pure luck, but broke consistently in newer unity/mono versions (a well known example is AVC/MiniAVC doing horribly thread unsafe things, which was likely not having major consequence pre-1.8 and started to break horribly with 1.8).

I've actually tried running a bunch of pre-1.8 plugins in 1.12, and most of them are actually working just fine (and the one that didn't didn't really break anything beside themselves). From an end user perspective, using very old, outdated plugins is a bad idea, but there are tons of "modern" plugins in the wild that are hopelessly broken as well, for a reason or another.

Regarding the exact case in point that this issue was about, it's difficult to be certain that a ReflectionTypeLoadException is due to the assembly being built against an old framework version. It could just as well be a missing dependency, or some other issue.

So in the end, I don't think it's a good idea to turn KSPCF into the plugin police, especially based on vague heuristics that may often not be actually valid.
