### ISSUE TITLE
Exception spam related to OnMouseUp() prevents clicking anything in editor

### ISSUE THREAD

**Issue by x13x54** [KSPModdingLibs/KSPCommunityFixes#171]
**Describe your problem with KSPCF :**
After a while in the editor, lots of exceptions spam my screen and log. Just as i was moving a control surface into place using offset. 
![image](https://github.com/KSPModdingLibs/KSPCommunityFixes/assets/84224121/de94d0d9-5be7-4678-86de-1e8cfa2975d7)
This issue occurs both on 1.32.0 and 1.32.1.
While the exceptions are happening, it becomes almost impossible to click anything as something goes terribly wrong with the OnMouseUp() event.
It might have something to do with me using the offset tool. As that is when this becomes noticeable. The click-issue is not permanent and it is possible to "sneak through" a click event every once in a while, switching between place and offset mode does seem to improve things a little.

**KSP version :** 1.12.5
**Link to your `KSP.log` file :** [KSP.log](https://github.com/KSPModdingLibs/KSPCommunityFixes/files/13625000/KSP.log)

**Comment by x13x54** [comment]
Simply clicking the save buttons also appears to throw the same kind of exceptions

**Comment by gotmachine** [comment]
I have some doubts this has anything to do with KSPCF.
The exceptions you're getting are related to some other mod, not sure which, but something that has PAW options like "kick mode", "target apogee", "cut at apogee", "target apside" ?

TBH, your log is littered with errors coming from everywhere, installing 300 mods is usually not gonna end well.
Could you uninstall KSPCF ? Assuming you can reproduce that issue consistently, I'm pretty sure you will get the exact same issue without it.

**Comment by x13x54** [comment]
I see. I tried without KSPCF and i haven't noticed the same issue. Maybe it's through KSPCF that the other mod's issue becomes noticable, or i haven't reached the same condition yet

**Comment by gotmachine** [comment]
See https://github.com/ErinaceusLinnaeus/BenjisHardwiredLogic/issues/2
