### ISSUE TITLE
Description of a vessel in the flight

### ISSUE THREAD

**Issue by yalov** [KSPModdingLibs/KSPCommunityFixes#18]
Ability to see editor's description of a vessel in the flight, 
for example in the "funds, science, rep" window.

![](https://i.imgur.com/y3WAekk.jpeg)

**Comment by Gordon-Dry** [comment]
How about the comments that you can write in VAB/SPH being readable in flight mode?
Actually those comments are without any use as long as they cannot be read in flight mode.
They are only good for making notes what is still to do in VAB/SPH when not finished building yet.

**Comment by gotmachine** [comment]
That comment isn't persisted with vessels, only on craft files. This mean I would have to implement a whole new thing to persist it at the vessel level. Moreover there is the issue that this information would be lost after docking (KSP doesn't provide any way to persist stuff after "merging" vessels).

So, to conclude, this is a whole new feature that probably belong to it's own mod. There is already at least one mod providing such a feature : https://forum.kerbalspaceprogram.com/index.php?/topic/199389-112x-vessel-notes-logs-full-release/

**Comment by yalov** [comment]
Ok, so now I understand why "vessel notes" is implemented as it is.
