### ISSUE TITLE
Zero cost Tech Tree nodes make parts impossible to unlock

### ISSUE THREAD

**Issue by afyber** [KSPModdingLibs/KSPCommunityFixes#180]
If you write a custom tech tree, such as via a patch file, with tech tree nodes other than the `start` node that have a cost of 0 those nodes will be "researched" at the start of the game. Meaning that the icon turns green, and child nodes become unlockable. This is all as you would expect. However, the parts in that node will not have been made available to purchase. The right-click information of the parts does not have the button to pay the unlock cost. The "Purchase X Parts [amount$]" Button below the node parts list does nothing when clicked. And none of those parts are included in the editor parts list like parts which have been researched, but not unlocked, usually do. This makes the parts impossible to ever use, since they're stuck in a state of researched, but not purchased, with no way to purchase them.

I highly suspect that some code is being run specifically for the root node of the tech tree, `id = start`, that allows the parts in it to be unlocked at the beginning of the game, and that is not being run for any other node.
Some pertinent code is the `Load(ConfigNode node)` function in `RDTech.cs`, which includes the lines
```C#
scienceCost = int.Parse(node.GetValue("cost"));
if (scienceCost == 0)
{
	state = State.Available;
}
```
Setting the tech node to `Available` (which I believe means "researched") if it has a cost of 0.

**Comment by JonnyOThan** [comment]
Thanks for the report - it would be helpful to have a simple MM patch I could drop into my GameData for testing.

**Comment by afyber** [comment]
Here you go, this will create a new node to the left of the start node and place the Mk1-3 Pod, Kickback booster, and Mystery Goo Experiment in the node's parts
[ZeroCostTechNode.txt](https://github.com/KSPModdingLibs/KSPCommunityFixes/files/14070817/ZeroCostTechNode.txt)
You'll have to change the filename to end in `.cfg`, since GitHub wouldn't let me upload it that way
