### ISSUE TITLE
Report: part variant nodes not working after 1.34

### ISSUE THREAD

**Issue by JonnyOThan** [KSPModdingLibs/KSPCommunityFixes#189]
[paste-f41208cebdbd0391.txt](https://github.com/KSPModdingLibs/KSPCommunityFixes/files/14112018/paste-f41208cebdbd0391.txt)
https://forum.kerbalspaceprogram.com/topic/204002-18-112-kspcommunityfixes-bugfixes-and-qol-tweaks/?do=findComment&comment=4363190

**Comment by JonnyOThan** [comment]
This is almost certainly the root issue.  Note that version 1.34 didn't directly touch this module.

```
[ERR 22:23:21.696] Module ModuleDynamicNodes threw during OnStart: System.NullReferenceException: Object reference not set to an instance of an object
  at ModuleDynamicNodes.InitializeNodeSets () [0x0002f] in <4b449f2841f84227adfaad3149c8fdba>:0 
  at ModuleDynamicNodes.OnStart (PartModule+StartState state) [0x00000] in <4b449f2841f84227adfaad3149c8fdba>:0 
  at Part.ModulesOnStart () [0x00120] in <4b449f2841f84227adfaad3149c8fdba>:0 
```

**Comment by JonnyOThan** [comment]
Can't reproduce locally.

**Comment by JonnyOThan** [comment]
[kspcf-189.json](https://github.com/KSPModdingLibs/KSPCommunityFixes/files/14120253/kspcf-189.json)

because I'm a masochist, I tried mirroring the install as closely as I could with CKAN.  The bug still didn't repro.

deviations from what's in the log:
```
Not indexed or not easily identifiable:

Benjee10_stowaway (not indexed)
kermangeddonindustries - stork delivery system
nereid - SAVE?
NFAeronaurticsWaterfall
soundtrackeditorforked
sterlingsystems
the_sea_four
thunderaerospace

not sure what is installed:
KerbalHacks
ContractPacks
KerboKatz
FruitKocktail 
wildblueindustries

eve/scatterer/stock vol clouds
opmVolumetricClouds

incompatible (on CKAN but could not install):

CommNetVisualisation
CommunityTraitIcons
Missing_robotics (requires making history, which was not installed in the original log)
poodsopmvo
PortraitStats (marked for 1.8, but depends on communitytraiticons)

```

**Comment by gotmachine** [comment]
Can you repost the log here if you still have it locally ? The user link on the forum is dead...

**Comment by JonnyOThan** [comment]
[paste-f41208cebdbd0391.txt](https://github.com/KSPModdingLibs/KSPCommunityFixes/files/14146182/paste-f41208cebdbd0391.txt)

Pretty sure it was this one.
