### ISSUE TITLE
Alarm Note doesn't preserve newline character on scene change

### ISSUE THREAD

**Issue by yalov** [KSPModdingLibs/KSPCommunityFixes#19]
https://bugs.kerbalspaceprogram.com/issues/28410

- create new sandbox game
- on KSC scene create alarm with the note: (one digit per line)
  > 1
  > 2
  > 3
- Change scene, for example go to VAB.
- Click on alarm, and then "Edit", to see note.
- Note will be: (all digits in one line)
  > 123

**Comment by yalov** [comment]
**UPD.**
Looks like the `.Replace("\n", "<br>")` fixes the problem.

**Comment by yalov** [comment]
also popup with the description on the mouse hover over alarm line in the Alarm Clock App would be helpful (same as in the KAC)

**Comment by gotmachine** [comment]
Fix added in release 1.12
