### ISSUE TITLE
Report: attachment node issues in 1.34

### ISSUE THREAD

**Issue by JonnyOThan** [KSPModdingLibs/KSPCommunityFixes#193]
https://forum.kerbalspaceprogram.com/topic/204002-18-112-kspcommunityfixes-bugfixes-and-qol-tweaks/?do=findComment&comment=4363606

Just filing this so I don’t forget to look at it.

**Comment by gotmachine** [comment]
From the report description, and since the log show tweakscale / KSP-recall is installed, this is very likely a duplicate of issue https://github.com/KSPModdingLibs/KSPCommunityFixes/issues/191

**Comment by JonnyOThan** [comment]
Ah yep good catch.
