### ISSUE TITLE
Performance: Ships with large numbers of engines are slow because of interleaved transform updates/raycasts

### ISSUE THREAD

**Issue by JonnyOThan** [KSPModdingLibs/KSPCommunityFixes#216]
Engines have to do a raycast to see if the thrust is obstructed.  In the stock code this happens in the engine module's FixedUpdate.  The problem is that this is basically interleaved with transform updates, and >90% of the cost of the raycasts is in syncing collider transforms.  If the engine raycasts were batched together, the sync would only need to happen once and it should be much faster.

![image](https://github.com/KSPModdingLibs/KSPCommunityFixes/assets/9804078/255d6f8b-844d-4f92-861c-1c1daf142a46)

**Comment by siimav** [comment]
Yup, that's what we already *solved* in SolverEngines.
https://github.com/KSP-RO/SolverEngines/commit/b3b7a95077913baa4f3795b5e6a77260aa3ad081

**Comment by JonnyOThan** [comment]
Awesome....I *think* we could incorporate some of that code in KSPCF since it's LGPL?

Also note that Solar panels have a similar problem.

**Comment by gotmachine** [comment]
Transform sync only happens *if* there was actually some changed transforms in between two separate engines fixedupdates, which will indeed be the case when gimbals are actively moving.

Batching the raycasts and engine damage execution at a deferred point of execution would indeed be ideal, but we should strictly limit that to stock modules, as we can't predict the behavior of modded engines (ie, SolverEngines...). Handling other modules that also perform raycasts (solar panels, radiators) would be more difficult as the core functionality of those modules is dependant on the raycasts results, so deffering execution would have even more consequences (and in the case of solar panels, there are definitely a lot of plugins either subclassing them or relying on the stock behavior).

Maybe a less intrusive solution would be to simply ensure a call to `Physics.SyncTransforms` is performed prior to the first raycast of any of those modules, then to disable `Physics.autoSyncTransforms` when the raycasts are performed.

**Comment by gotmachine** [comment]
Fix implemented in https://github.com/KSPModdingLibs/KSPCommunityFixes/pull/220/

**Comment by gotmachine** [comment]
Released in 1.35.0
