### ISSUE TITLE
Feature idea : integrate Making Less History into KSPCF

### ISSUE THREAD

**Issue by kurgut** [KSPModdingLibs/KSPCommunityFixes#218]
This mod still works in 1.12, but I believe it would be nice to have its featues integrated in KSPCF, since it improves performances. Plus the said mod is only marked compatible to 1.7.3, which makes it much less visible to the player base.
MLH repo here : https://github.com/DMagic1/KSP_MakingLessHistory

Would need to ask DMagic about it of course.

Thank you : )

**Comment by gotmachine** [comment]
I'm not against having such a feature, but with the following caveats : 
- KSPCF is a big bag of stuff and users never read through everything it does before installing it, so the usual policy is to avoid doing anything that deviate from stock behavior. Therefore, this should be a disabled by default option, and I'm not too keen on having it as another annoying blocking popup asking for that choice on loading (even if it's a one time popup), in which case this will end up being not very discoverable for the vast majority of users.
- Independently of how this is handled, we should advertise explicitly that this effectively disable all the expansion features, including the additional launch sites.
- I don't like how this is implemented in MakingLessHistory, by temporarily renaming a file on the user drive. This can lead to the expansion being permanently disabled, typically in the scenario where KSP crashes or hangs at any time during loading, leading the user to uninstall MakingLessHistory (as removing recently installed mods is the usual thing to do in such a case), leaving the KSP install with a permanently disabled expansion. If such a feature is to be added to KSPCF, the likely best way to do it would be by patching the `ExpansionsLoader.InitializeExpansion()` coroutine, breaking from it immediately if the `string expansionFile` argument is matching the MH expansion file.

**Comment by gotmachine** [comment]
Implemented in 1.35.0
