### ISSUE TITLE
Is it at all possible to patch DirectStorage support in with this?

### ISSUE THREAD

**Issue by unquietwiki** [KSPModdingLibs/KSPCommunityFixes#23]
https://devblogs.microsoft.com/directx/directstorage-api-available-on-pc/

I know Harmony is supposed to do some heavy lifting on patching games above their shipped APIs. I was curious if this new development could be leveraged here to reduce KSP load times.

**Comment by gotmachine** [comment]
1. I doubt there is any way to leverage DirectStorage. I don't think even the most recent beta versions of Unity support it, and the Unity version KSP is built on certainly doesn't. I haven't verified this in detail, but I would be very surprised if there is a way to have Unity and DirectStorage working together without explicit support on the Unity side.

2. I doubt DirectStorage and similar "direct SSD to GPU memory" technologies would give significant gains for KSP :
  - As far as I know, KSP load all assets in memory during loading, so the "texture streaming" part doesn't apply.
  - Asset loading is arguably a not so big part of the overall loading process. At least 2/3 of the loading screen time is spent building the game database from the configs. This is where the real KSP inefficiency lies. This being said, it starts to matter a bit more when texture heavy planet packs and visual mods are used.

If someone want to explore that possibility, no problem, but this not something I'm interested in.
