### ISSUE TITLE
Search in the Part Editor of parts with none category

### ISSUE THREAD

**Issue by yalov** [KSPModdingLibs/KSPCommunityFixes#234]
The known feature is that if the category is none, than a part is hidden from the parts search.

As I understand, an asteroid part or a kerbal part have a category equal to none and therefore cannot be searchable — that is good.

A problem is a conflict with "Community Category Kit" mechanic, what is getting worse with the Community Parts Titles Extras: CCK - No Duplicates — in this scenario,  a part could be in the cck category, but be hidden from the stock category (has category set to none), and therefore not searchable.

One of the solution would be to search all parts, but hardcode exclude kerbals, asteroid and comet. 
I am not familiar with other "special" parts (stock or mods) that need to be exluded.

**Comment by nagleaidan** [comment]
That sounds like a problem for CCK to fix, not this mod

**Comment by yalov** [comment]
The default behavior of disabling search for parts with no category is questionable and generally unexpected. 

I believe parts should remain searchable even if they are hidden from all categories, whether intentionally or unintentionally, in the simple (one-column) view in the editor.

**Comment by Rodg88** [comment]
Having category = none is actually used to specifically hide parts in some cases, particularly when soft-deprecating parts to prevent their use without outright deleting them.

**Comment by nagleaidan** [comment]
> The default behavior of disabling search for parts with no category is questionable and generally unexpected. 
> 
> 
> 
> I believe parts should remain searchable even if they are hidden from all categories, whether intentionally or unintentionally, in the simple (one-column) view in the editor.

This is a feature, you may disagree with it but it's still a feature. This mod is designed for fixing bugs, not altering features. If you want to change this, make a separate mod.

**Comment by yalov** [comment]
I agree that CCK itself would be a better place for this setting — but that will never happen.
And CCK is very popular, based on CKAN download count.

Also I would add the full search in the "Community Parts Titles Extras: CCK - No Duplicates" if I would know how to work with Harmony.

Maybe It could be a KSPCommunityFixes setting, disabled by default, what could enable search for everything, even for asteroid, kerbalEVA, and soft-deprecating parts? 

I still prefer to have several deprecated parts in the search results rather than be unable to find a properly loaded part due to some CCK-related patch incompatibility.

**Comment by JonnyOThan** [comment]
> I still prefer to have several deprecated parts in the search results rather than be unable to find a properly loaded part due to some CCK-related patch incompatibility.

Isn’t this solvable with a simple MM patch that changes the category of all parts that have it set to `none`?

**Comment by yalov** [comment]
> Isn’t this solvable with a simple MM patch that changes the category of all parts that have it set to none

OMG, it looks like setting the category to any string other than "none" or an existing stock category makes the part searchable but does not make it appear in the stock category.

**Comment by yalov** [comment]
Is it in the scope to make a new default "hidden" enum that is well, hidden, and does not showed as category in the gui?

**Comment by gotmachine** [comment]
I will rejoin what others have said.

There is no fundamental issue or problematic behavior in the stock code. 

CCK is the mod providing the custom categories feature, it should be it handling the implementation so everything works as expected. In the end, if me or anyone decide to fix that issue, it should be done in CCK, not here.
