### ISSUE TITLE
`ForceSyncSceneSwitch` patch cause the parts PAW UI to be as if they were in flight after reverting to VAB

### ISSUE THREAD

**Issue by JonnyOThan** [KSPModdingLibs/KSPCommunityFixes#260]
I got a report from someone who was using the standalone dll from https://github.com/KSPModdingLibs/KSPCommunityFixes/pull/250

> and also, whenever you revert to VAB with that scene switch patch, it treats parts as though you're still in flight
ie, can't change subtypes, other editor stuff
only flight stuff

**Comment by siteonfly** [comment]
Confirm after updating to 1.36

**Comment by siimav** [comment]
Culprit has already been found: #273

**Comment by gotmachine** [comment]
> Confirm after updating to 1.36

What exactely is happening in your case ? We identified a mod compatibility issue with Universal Storage, but what happens with that issue doesn't really match the "parts are treated as if they were still in flight after reverting to the VAB". Can you expand a bit and upload your ksp.log ?

**Comment by siteonfly** [comment]
After revert I cant change some params, for example SRB's max throtle, command pods kerbalism settings, service bays appearance and etc. 
![before_launch](https://github.com/user-attachments/assets/c036fd58-d9f1-4b3b-9556-0e5a8efd460a)

**Comment by siteonfly** [comment]
Forget to notice that I also have US2 installed

**Comment by JonnyOThan** [comment]
Confirmed that I can repro with kspcf 1.36.0 and US2, and does not repro without US2.
