### ISSUE TITLE
FastLoader causing launch hang/crash with certain mods, with or without KSPCF

### ISSUE THREAD

**Issue by michaelproeber** [KSPModdingLibs/KSPCommunityFixes#261]
**Issue** -- After opting into the .png caching FastLoader feature, my modded game fails to load upon trying to load certain mod assets. It appears that the cached .png files were corrupted, and they aren't being overwritten by KSPCF. 

When I try launching the game without KSPCF, with the mods in question (A330neo and NearFutureAeronautics), the launch hangs at the same mod assets, while the game animations continue. Is there a way to clear the cached assets for those mods? Since they are unrelated and the other NearFuture mods work, I assume both were just mutually caught in a snag. Without both mods, my game launches.

It occurs even if textureCacheEnabled is false in PNGTextureCache.cfg. Re-enabling it did not rebuild the cache. Disabling DragCubeGeneration makes no difference. 

**KSP Version** -- 1.12.4

[Log file](https://github.com/user-attachments/files/17351624/KSP.log); **Error message** -- `Loading has failed due to an unhandled error

Failure in subsystem : Part compilation
Part: Trent 7000 Jet Engine (A330neo/KK_Trent7000/KK_Trent7000)

System.NullReferenceException: Object reference not set to an instance of an object
  at ModuleResourceIntake.GetInfo () [0x0002d] in <0435390348b6470d8166bd1c53b4b100>:0 
  at PartLoader.CompilePartInfo (AvailablePart newPartInfo, Part part) [0x0024e] in <0435390348b6470d8166bd1c53b4b100>:0 
  at (wrapper dynamic-method) PartLoader+<CompileParts>d__56.PartLoader+<CompileParts>d__56.MoveNext_Patch0(PartLoader/<CompileParts>d__56)
  at KSPCommunityFixes.Performance.KSPCFFastLoader+<FrameUnlockedCoroutine>d__63.MoveNext () [0x0006c] in <d08a67791ddc409fad78e1e6485c71dc>:0 `

Similar error with NearFutureAeronautics.

**Comment by gotmachine** [comment]
Given that your game still fail to load when KSPCF is not installed, there is no way this can be caused by KSPCF. 

The cached png files are not recognized in any way by the the stock game, and they would have been deleted anyway when you removed KSPCF, as they are stored in the `KSPCommunityFixes\PluginData` directory. KSPCF doesn't alter any of the game or mod files, and neither does it write files elsewhere.
