### ISSUE TITLE
Drag not correct when procedural fairings

### ISSUE THREAD

**Issue by roxik0** [KSPModdingLibs/KSPCommunityFixes#280]
**Describe your problem with KSPCF :**
Drag Cubes are incorrect for Procedural Fairings see attached picture they are not taking "procedural" shape into account.
**KSP version :** 1.12.5
**Link to your `KSP.log` file :**
![image](https://github.com/user-attachments/assets/966cb2ad-66e2-4c67-bf12-7414e5b70f47)

**Comment by roxik0** [comment]
I;m stupid now I see that there are two settings there.. but I don't know why default is prefab instead of actural part :)

**Comment by gotmachine** [comment]
> I don't know why default is prefab instead of actural part :)

Because for the vast majority of parts, the drag cube that will be used is defined by the prefab, not the actual part.
Fairings (and other procedural parts from mods) are an exception to this general rule.
