### ISSUE TITLE
Mark auto-saved ship in launchpad launch dialog

### ISSUE THREAD

**Issue by Tuupertunut** [KSPModdingLibs/KSPCommunityFixes#30]
**Problem:**
When launching a craft in the launchpad/runway launch dialog, there are sometimes two crafts with the same name. One of them is an auto-saved craft and one is manually saved, but there is no way to tell which is which. Often they differ in subtle ways, such as staging, and selecting the wrong one might result in a failure.
![launchpad](https://user-images.githubusercontent.com/1782631/163494905-98c54367-3fc0-4c56-8092-1d38c76386cc.png)

**Solution:**
Mark an auto-saved ship in the launchpad/runway launch dialog with a text that says "[Auto-saved ship]". This is already done in the VAB load dialog (see the first and last crafts):
![vab](https://user-images.githubusercontent.com/1782631/163495136-0f33fd22-e19a-4433-be45-144526575e5c.png)

**Comment by gotmachine** [comment]
Fix added in release 1.12
