### ISSUE TITLE
Performance issue: ProgressTracking.Update seems to be O(bodies * vessels)

### ISSUE THREAD

**Issue by JonnyOThan** [KSPModdingLibs/KSPCommunityFixes#55]
In my "twitch plays KSP" stream I have a game save with galaxies unbound + lots of other planet packs (320 bodies in total) and LOTS of kerbals.  It was running slow so I decided to attach a profiler and was astonished to see this: 
![image](https://user-images.githubusercontent.com/9804078/178519114-54776cea-7c85-4361-8cd1-5d91e6e30940.png)

A brand new save in the same universe has ProgressTracking.Update at about 5ms, which is still astonishingly high but is likely related to the number of bodies.

I haven't looked into what this function is doing, but it would be awesome to optimize this.

**Comment by JonnyOThan** [comment]
Er it's worse than I thought....the top-level seems to iterate over every vessel, and then over every ProgressNode

**Comment by gotmachine** [comment]
TBH, I would categorize that as "won't fix". KSP just doesn't scale well at all in some modded scenarios.

320 bodies is just silly. If a mod (or a player) want to do that, then it should be responsible for implementing such a case properly.

I can take a look, but it seem entirely normal for progress tracking to check all vessels, not only the active one. Not saying there isn't room for optimization while keeping stock functionality intact, but I think that having such a large amount of bodies will inevitably cause perf issues in many places, so I don't really see the point, and it's kinda out of the scope of KSPCF to deal with that.

**Comment by JonnyOThan** [comment]
Galaxies Unbound with all the optional planets is 100-200 bodies I think.  And I'm pretty sure the stock code isn't excluding asteroids, flags, and debris.

**Comment by JonnyOThan** [comment]
I recognize my install is an extreme one, but this change increases my fps by ~50% (33% reduction in frame time)
