### ISSUE TITLE
Performance issue: CommnetNetwork.Update is slow

### ISSUE THREAD

**Issue by JonnyOThan** [KSPModdingLibs/KSPCommunityFixes#56]
I have a save with a lot of vessels and bodies in flight, and this function is roughly 11% of the frame time:
![image](https://user-images.githubusercontent.com/9804078/178520740-f366fd36-be31-4911-ae2d-aa2a13743e4e.png)

Is there anything that can be done to optimize it?

**Comment by gotmachine** [comment]
I doubt it. Commnet has some operations that are by nature O^(body count) and O^(vessel count).
As far as I know, CommNet is decently optimized. 

I believe the only way to any significant improvement would be to re-implement it entirely using burst/jobs (see what RealAntennas is doing for example), which would be a large project in itself. I doubt a regular managed threaded implementation would help much.

**Comment by JonnyOThan** [comment]
Two things:
-it looks like there is some throttling code in there - if I understand it correctly, it's only supposed to update every 5 seconds for an unpacked vessel and every 0.5 seconds for a packed one.  Empirically, this is not working and it's updating every frame.

-A naive system that checks every pair of vessels would be O(vessels^2) but it should be possible to leverage the nature of local clusters to cut down on the amount of work to do.  You can calculate the antenna strength required at each body to reach each other body, and then just skip pairs that are clearly too far.  But I'm speculating here.

**Comment by gotmachine** [comment]
> it's only supposed to update every 5 seconds for an unpacked vessel and every 0.5 seconds for a packed one. Empirically, this is not working and it's updating every frame.

Do you have Kerbalism installed ? It specifically disable the CommNet throttling. Other mods might also be doing that.

I don't say there isn't room for performance improvements, but I'm not willing to include quick-and-dirty "lets disable that" patches that will have unwanted side effects at one end or another of the modding ecosystem.

I would suggest first identifying exactly where the performance bottlenecks are. If you find ways to improve perf while keeping both user facing functionality and API surface 1:1 with stock, that would be great, but I don't have much hope.
