### ISSUE TITLE
MapObject icons appear in flight view

### ISSUE THREAD

**Issue by JonnyOThan** [KSPModdingLibs/KSPCommunityFixes#61]
![image](https://user-images.githubusercontent.com/9804078/179086727-4b573ec2-b713-4a30-b78b-31b522f9627b.png)

This is why I was calling OrbitRenderer.LateUpdate manually - it needs to go through once to set the MapObjects visibility properly.  Might be able to make this patch a little more complex to account for that?

**Comment by JonnyOThan** [comment]
Well, let me test a bit more in isolation, it's possible I have some local stuff still polluting this build.

**Comment by JonnyOThan** [comment]
Yep, confirmed this occurs with the official release too

**Comment by gotmachine** [comment]
Missed that after simplifying the patch to an early bail out from LateUpdate.
Fix is incoming.

**Comment by gotmachine** [comment]
Should be fixed in 1.19.1
