### ISSUE TITLE
Proposal for some .cfg based fixes

### ISSUE THREAD

**Issue by sunnypunny** [KSPModdingLibs/KSPCommunityFixes#62]
Some fixes for your consideration:

**[Missing stock agencies](https://github.com/sunnypunny/KerbalWitchery/tree/release/GameData/KerbalWitchery/Agencies):** there are 2 agencies in the base game without AGENCY nodes or logos (Light Year Tire Company + Stratus Corporation). These agencies are listed as the manufacturers of several parts each. When part test contracts are offered the system seems to prefer using the manufacturer as the agency providing the contract and with these parts it's unable to do so. A while ago I contacted the author of Kerbalized Flags who provided some great logos for them and gave permission to do whatever with them.

![LightYear256](https://user-images.githubusercontent.com/10196270/179258605-08da9626-0a7b-4e1d-87c3-ed135600c926.png)

![Stratus256](https://user-images.githubusercontent.com/10196270/179258636-2ceb7ff4-7c71-47fd-b283-f0e5366c4aaf.png)

Another widely mentioned agency is Clamp-O-Tron, it's not listed as a manufacturer (aside from the radial attachment port being found behind their factory) but I think everyone is familiar with their docking ports.

![ClampOTron256](https://user-images.githubusercontent.com/10196270/179258844-49c15442-b041-453e-bdcc-74b8df7db9a0.png)

When trying to complete all agency and manufacturer fields I found one was missing for the parachutes, so I asked the logo author if they wanted to make another one and they came up with Free Fall Parachutes. This one would be the most out of scope since it's not mentioned anywhere in the base game but it's still worth including here.

![freefall256](https://user-images.githubusercontent.com/10196270/179259223-052c7fed-b05f-412d-9aea-9b9599514604.png)

All these are included in a mod I'm working on (linked above) but I think they'd be more suited to this project, particularly with the logos being community-sourced.

**[Inconsistent/missing part manufacturers](https://github.com/sunnypunny/KerbalWitchery/blob/release/GameData/KerbalWitchery/Agencies/ManufacturerFixes.cfg):** Several parts have inconsistent and missing manufacturer values, this is an easy fix and if using the added agencies above almost every part's manufacturer can be a named agency.

There's room to debate who should manufacture the Flea and Hammer boosters, the winglet and the service bays so my choices there could be changed.

**[Inaccurate bulkhead profiles](https://github.com/sunnypunny/KerbalWitchery/blob/release/GameData/KerbalWitchery/Parts/BulkheadProfiles.cfg):** A lot of parts have inaccurate bulkhead profile values (mostly surface attach parts), also mk0 and mk1 profiles are missing if these are considered to be separate from size0 and size1. The linked file contains fixes for these. The mk0 and mk1 fixes may be unsuitable given that the base game's only use for this field seems to be the editor sorting list, and mk0 + mk1 profiles would be missing icons, so you may only want the surface attach fixes here.

Let me know if you want any of these and I can do up a pull request and remove them from my mod.

**Comment by sunnypunny** [comment]
Forgot to add one more:

**[Stock contracts fixes](https://github.com/sunnypunny/KerbalWitchery/blob/release/GameData/KerbalWitchery/Career/Contracts.cfg):** A few parts test contracts are missing for the small rover wheel, smaller SRBs and MonoProp engine. In the linked file I also added some extra situations for a few contracts that seemed suitable along with surveys for the Magnetometer, Mystery Goo and Materials Bay.

**Comment by sunnypunny** [comment]
Ok, I'll put that together shortly

Did you have any preference for the directory structure? I can't see any other similar types of fixes so I guess a new folder labelled "Configs" with all this stuff inside, maybe with another subdirectory for the logos

**Comment by gotmachine** [comment]
There is currently a `Patches` directory for mod support patches. I would suggest renaming it `ModSupportPatches`, and creating a `StockConfigsPatches` next to it, with an `Icons` subfolder for the `*.png` files

**Comment by sunnypunny** [comment]
thanks, submitted here https://github.com/KSPModdingLibs/KSPCommunityFixes/pull/64
