### ISSUE TITLE
Robotics extension/position field reset to default after scene switch

### ISSUE THREAD

**Issue by gotmachine** [KSPModdingLibs/KSPCommunityFixes#72]
From forum user [Thatguywholikesionengines](https://forum.kerbalspaceprogram.com/?app=core&module=members&controller=profile&id=160854) :
>I'm using a docking port attached to a robotic piece on an SSTO for space reasons. I leave it extended while i go do other things with other craft for clearance issues. I come back, undock, and try to retract the robotic bit - But it's reset to zero extension. Extending the robotic piece just makes it stick out unnaturally far. 

Something similar was reported on Discord. Unsure what could be causing this, needs investigation.

**Comment by RBQcat** [comment]
This bug also resets the action group.

**Comment by gotmachine** [comment]
Seems somewhat related : https://forum.kerbalspaceprogram.com/index.php?/topic/204002-18-112-kspcommunityfixes-bugfixes-and-qol-tweaks/&do=findComment&comment=4198850
