### ISSUE TITLE
Release 1.21.0 breaks LY-10 landing gear

### ISSUE THREAD

**Issue by Test-Account-KSP** [KSPModdingLibs/KSPCommunityFixes#89]
LY-10 landing gear has a scaling control. After updating KSP Community Fixes to 1.21.0 the scaling control disappeared from PAW and the gear became scaled to 1.00 size. Reverting to previous version fixed the problem (the scaling control reappeared, the front gear returned to proper scaling 0.7, wing gear to 0.75)
![screenshot25](https://user-images.githubusercontent.com/110846612/187697677-e9856172-8d41-4203-87ca-ee4b06dd5086.png)

**Comment by Test-Account-KSP** [comment]
It works now

**Comment by NathanKell** [comment]
I am deeply confused. How did it start working?

**Comment by NathanKell** [comment]
(and/or break in the first place, but given it's working now with no change to KSPCF...)
