### ISSUE TITLE
Parts with VARIANTs have wrong mass in catalog

### ISSUE THREAD

**Issue by lpgagnon** [KSPModdingLibs/KSPCommunityFixes#93]
Feels like the sort of stock bug in kspcf's purview to fix: when a part is configured to have VARIANTs, the parts catalog only takes the VARIANT's mass into account, not the part's own mass field, resulting in too-low masses being reported. Rest of the game correctly(?) adds them up.

Example (from RO): 
![](https://media.discordapp.net/attachments/319857228905447436/1004025612391952494/Screen_Shot_2022-08-02_at_09.58.50.png)

Originally discovered here: https://discord.com/channels/319857228905447436/319857228905447436/1004119231325032649

**Comment by NathanKell** [comment]
Thanks I'll try to take a stab this weekend.

**Comment by NathanKell** [comment]
This is not a stock KSP bug, as can be seen by checking out a part with variants in stock KSP. It is probably an interaction with something else that does GetModuleMass things.

**Comment by NathanKell** [comment]
@lpgagnon my hunch is that this is an RF bug, since that's what's most likely to be varying the part's mass also using GetModuleMass so if you're bored it'd be awesome if you could double check. Either way though I've confirmed it's not happening on stock Squad parts with partvariants...
